### ISSUE TITLE
Rig check

### ISSUE THREAD

**Issue by nathanbillis** [Jbithell/ParadisePi#8]
Add the ability to check the rig using the panel, this could be a button that's on the admin panel that takes you to a rig check screen that will allow you to go through all the channels fading in and out allowing the LD to quickly check the rig.

**Comment by cherry-john** [comment]
Is this in addition to the channel keypad in the lighting tab?

**Comment by Jbithell** [comment]
I think it's a faster version of dialing in every channel manually

**Comment by cherry-john** [comment]
added in c383d2d20c5e9801ae301ab85ce1893d45b416bc
